/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface TeamMemberProps {
  name: string;
  description: string;
  imageSrc: string;
  socialIconSrc: string;
}

const TeamMember: React.FC<TeamMemberProps> = ({
  name,
  description,
  imageSrc,
  socialIconSrc,
}) => {
  return (
    <article className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow text-center text-red-600 rounded-none max-md:mt-8">
        <div className="flex flex-col pb-7 pl-12 bg-orange-50 border-red-600 border-solid border-[3px] rounded-[175px] max-md:pl-5">
          <img
            loading="lazy"
            src={imageSrc}
            alt={`${name}'s profile`}
            className="object-contain z-10 self-end mt-0 max-w-full rounded-full aspect-square w-[217px]"
          />
          <h3 className="self-center mt-5 text-2xl font-bold">{name}</h3>
          <p className="self-start mt-1 text-[12px] text-slate-700 h-auto">
            {description}
          </p>
        </div>
        <img
          loading="lazy"
          src={socialIconSrc}
          alt="Social media icons"
          className="object-contain self-center mt-10 max-w-full aspect-[10] w-[250px]"
        />
      </div>
    </article>
  );
};

export default TeamMember;
