/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Login from "./components/Login";
import Register from "./components/Register";

const Auth: React.FC = () => {
    return (
        <main className="flex flex-col justify-center items-center pt-[130px] h-auto">
            <div className="flex flex-col max-sm:h-full  items-center">
                <main className="flex flex-row max-sm:flex-col h-auto py-[30px]">
                    <Login />
                    <Register />
                </main>
            </div>
        </main>
    );
};

export default Auth;
