/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FoodMenuItem from "./FoodMenuItem";
import { IFoodItem } from "../../../../types/IFood";

interface FoodMenuColumnProps {
    items: IFoodItem[];
}

const FoodMenuColumn: React.FC<FoodMenuColumnProps> = ({ items }) => {
    return (
        <div className="flex flex-col max-sm:w-full  w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col w-full max-md:mt-10 max-md:max-w-full">
                {items.map((item, index) => (
                    <div key={index} className={index > 0 ? "mt-8" : ""}>
                        <FoodMenuItem {...item}/>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default FoodMenuColumn;
