/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FoodMenuColumn from "./FoodMenuColumn";


import { IFoodItem } from "../../../../types/IFood";

interface FoodMenuProps {
    items: IFoodItem[];
}

const FoodMenu: React.FC<FoodMenuProps> = ({
    items,
}) => {
    const leftColumnItems = items.slice(0, 3);
    const rightColumnItems = items.slice(3);
    return (
        <main className="flex flex-col md:px-[100px] pt-5">
            <section className="w-full max-md:max-w-full">
                <div className="flex gap-5 max-md:flex-col">
                    <FoodMenuColumn items={leftColumnItems} />
                    <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                        <img
                            loading="lazy"
                            src="https://cdn.builder.io/api/v1/image/assets/TEMP/c8cce017380ef412439d973dd7de2d9d1311e6eb0bc13e14210d4d515d9fc423?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109"
                            alt="Featured dish"
                            className="grow w-full h-full shadow-sm aspect-[1.03] max-md:mt-10 max-md:max-w-full"
                        />
                    </div>
                </div>
            </section>
            <section className="mt-8 max-md:mr-2 max-md:max-w-full">
                <div className="flex gap-5 max-md:flex-col">
                    <FoodMenuColumn items={rightColumnItems.slice(0, 2)} />
                    <FoodMenuColumn items={rightColumnItems.slice(2,4)} />
                </div>
            </section>
        </main>
    );
};

export default FoodMenu;
