/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Testimonial: React.FC = () => {
  return (
    <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow max-md:mt-10 max-md:max-w-full">
        <h3 className="self-center text-xl font-bold text-red-600">
          Testimonial
        </h3>
        <h2 className="mt-4 mr-11 ml-7 text-4xl font-bold text-red-600 max-md:mx-2.5">
          <span className="text-slate-700">Review</span> form our guests
        </h2>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/42b6d8650633974f0d4f4046ab81ee7ded7799df44228fe69f510950f024d844?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109"
          alt="Bernadette R. Martin"
          className="object-contain self-center mt-8 max-w-full rounded-full aspect-square w-[100px]"
        />
        <p className="self-center mt-4 text-2xl text-center text-slate-700">
          Bernadette R. Martin
        </p>
        <p className="self-start mt-4 text-lg text-center text-slate-700 max-md:max-w-full">
          Also very good and so was the service. I had the mushroom risotto with
          scallops which was awesome. My wife had a burger over greens ...
        </p>
        <div className="flex flex-col self-end mt-10 max-w-full w-[285px]">
          <div className="flex gap-2.5 self-end">
            {[1, 2, 3, 4].map((_, index) => (
              <img
                key={index}
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/57d865fe929ab232f13b73dbc04966fe33b9939d08325aaece8205a06f70d492?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109"
                alt=""
                className="object-contain shrink-0 w-5 aspect-[1.05]"
              />
            ))}
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/f9165c4333d6cb7e26951a4b120935bed7e24eae721bd9703d0adcc642d3bded?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109"
              alt=""
              className="object-contain shrink-0 w-5 aspect-[1.05]"
            />
          </div>
          <div className="flex gap-2.5 self-start mt-8">
            {[1, 2, 3, 4].map((_, index) => (
              <div
                key={index}
                className={`flex shrink-0 w-5 h-5 rounded-full border-2 border-red-600 border-solid stroke-[2px] stroke-red-600 ${
                  index === 2 ? "bg-red-600 fill-red-600" : ""
                }`}
              />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Testimonial;
