/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ImageCard from "./ImageCard";

const BigOffer: React.FC = () => {
  const images = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/88c49fb39d16344908ad1e2b1c9506efd4f0079148edbe831499bc93d3a5fb66?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109",
      alt: "Food item 1",
      className: "w-[29%] max-md:ml-0 max-md:w-full aspect-[2.03]",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/508547762c050ec65a083f7cf9ca25eccde2a0b0d2b811449676ddd30554072b?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109",
      alt: "Food item 2",
      className: "ml-5 w-2/5 max-md:ml-0 max-md:w-full aspect-[2.8]",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/TEMP/04c302adac072d0240e1275d9074d6491048afa45e1d3143f4ef6120675e9c61?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109",
      alt: "Food item 3",
      className: "ml-5 w-[31%] max-md:ml-0 max-md:w-full aspect-[2.16]",
    },
  ];

  return (
    <section className="flex flex-col items-center">
      <h1 className="text-5xl italic font-extrabold text-red-600 max-md:text-4xl">
        Bigg Offer
      </h1>
      <p className="mt-4 text-xl font-bold text-slate-700 max-md:max-w-full">
        For in this week, take your food, buy your best one.
      </p>
      <div className="self-stretch mt-6 w-full max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          {images.map((image, index) => (
            <ImageCard key={index} {...image} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default BigOffer;
