/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ImageCardProps {
  src: string;
  alt: string;
  className?: string;
}

const ImageCard: React.FC<ImageCardProps> = ({ src, alt, className }) => (
  <div className={`flex flex-col ${className}`}>
    <img
      loading="lazy"
      src={src}
      alt={alt}
      className="object-contain grow w-full"
    />
  </div>
);

export default ImageCard;
