/**
 * This code was generated by Builder.io.
 */
import React from "react";

const OurStorySection: React.FC = () => {
  return (
    <section className=" w-full max-w-[1052px] max-md:mt-10 max-md:max-w-full pt-[50px]">
      <h2 className="text-4xl font-bold text-justify text-red-600">
        OUR STORY
      </h2>
      <div className="flex gap-5 mt-7 max-md:flex-col">
        <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
          <p className="mt-5 text-lg text-justify text-slate-700 max-md:mt-10 max-md:max-w-full">
            Lorem Ipsum is simply dummy text of the printing and typesetting
            industry. Lorem Ipsum has been the industry's standard dummy text
            ever since the 1500s, when an unknown printer took a galley of type
            and scrambled it to make a type specimen book. It has survived not
            only five centuries, but also the leap into electronic typesetting,
            remaining essentially unchanged. It was popularised in the 1960s
            with the release of Letraset sheets containing Lorem Ipsum passage
          </p>
        </div>
        <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/6f9cd253ca538844dd7da6c5fb0294e5183260ba00df1d238cbb9494dc9c2017?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109"
            alt="Our story illustration"
            className="object-contain grow w-full aspect-[1.74] max-md:mt-8 max-md:max-w-full"
          />
        </div>
      </div>
    </section>
  );
};

export default OurStorySection;
