/**
 * This code was generated by Builder.io.
 */
import React from "react";

const StorySection: React.FC = () => {
  return (
    <section className="px-16 py-11 mt-8 w-full rounded-3xl border-red-600 border-solid border-[3px] max-w-[1173px] max-md:px-5 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/6bb4785edfcc9bdfa31cfcb1ca2701b5de6c28b0e50e48c9ee2502692787e760?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109"
            alt="Company story illustration"
            className="object-contain grow w-full rounded-3xl aspect-[1.74] max-md:mt-10 max-md:max-w-full"
          />
        </div>
        <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
          <div className="flex flex-col self-stretch my-auto text-justify text-slate-700 max-md:mt-10 max-md:max-w-full">
            <h2 className="text-xl font-bold max-md:max-w-full">
              Opaleye yellowtail snapper, velvet catfish, graveldiver banded
              killifish, Old World rivuline catalufa eagle ray Moorish idol.
            </h2>
            <p className="mt-14 text-lg max-md:mt-10 max-md:max-w-full">
              Queen danio velvet catfish Sacramento blackfish, bullhead shark,
              Colorado squawfish Russian sturgeon clown triggerfish swamp-eel
              paradise fish. Hake cookie-cutter shark silver carp hawkfish snipe
              eel armorhead catfish, moray eel silverside! Bluegill toadfish,
              orangespine unicorn fish. Manta Ray Moorish idol
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default StorySection;
