/**
 * This code was generated by Builder.io.
 */
import React from "react";
import MenuHeader from "./MenuHeader";
import MenuTabs from "./MenuTabs";
import MenuSection from "./MenuSection";
import ViewAllMenuButton from "./ViewAllMenuButton";

const menuItems = [
  {
    name: "Gazpacho Garlic",
    description: "Chilled tomato, cucumber, garlic, red pepper soup.",
    price: "$55",
  },
  {
    name: "Pan Con Berenjina Frita",
    description: "Fried aubergine with almond on bread (2 pieces).",
    price: "$40",
  },
  {
    name: "New Lubina Marinada",
    description: "Marinated seabass with sour sauce & coriander on bread.",
    price: "$45",
  },
  {
    name: "Gazpacho",
    description: "Atlantic cod fillet, chips, salad, tartare, lemon.",
    price: "$35",
  },
  {
    name: "Coconut Chia Bowl",
    description: "Marinated seabass with sour sauce & coriander on bread.",
    price: "$95",
  },
];

const Menu: React.FC = () => {
  return (
    <main className="flex flex-col items-center md:px-[100px]">
      <MenuHeader
        title="SPECIALS"
        subtitle="Check out our menu"
        description="Demoralized by the charms of pleasure of the moment so blinded except to some advantage."
      />
      <MenuTabs
        tabs={["BREAKFAST", "LUNCH", "DINNER", "STARTERS", "BEVERAGES"]}
        activeTab="BREAKFAST"
      />
      <div className="self-stretch mt-5 max-md:mr-1 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col w-full max-md:mt-10 max-md:max-w-full">
              <div className="flex flex-wrap gap-3.5">
              
                <div className="flex flex-col grow shrink-0 basis-0 w-fit max-md:max-w-full">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/8fa983c00fbd93fe26609bb2d5c06e0aec611827c2f1dad9f61c4c4d58e5d613?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109"
                    className="object-contain w-full aspect-[0.79] max-md:max-w-full"
                    alt=""
                  />
                </div>
              </div>
              <ViewAllMenuButton />
            </div>
          </div>
          <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
            <MenuSection items={menuItems} />
          </div>
        </div>
      </div>
    </main>
  );
};

export default Menu;
