/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface MenuItemProps {
  name: string;
  description: string;
  price: string;
}

const MenuItem: React.FC<MenuItemProps> = ({ name, description, price }) => (
  <div className="flex flex-wrap gap-3 max-w-full text-red-600 w-auto">
    <div className="flex flex-col grow shrink-0 items-start text-2xl basis-0 w-fit max-md:max-w-full">
      <h3>{name}</h3>
      <p className="mt-2.5 text-lg text-slate-700">{description}</p>
      <div className="shrink-0 self-stretch mt-2.5 h-0.5 bg-red-600 border-2 border-red-600 border-dashed max-md:max-w-full" />
    </div>
    <div className="flex flex-col self-end mt-14 text-xl font-bold whitespace-nowrap max-md:mt-10">
      <div>{price}</div>
    </div>
  </div>
);

export default MenuItem;
