/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ViewAllMenuButton: React.FC = () => (
    <button className="flex flex-wrap gap-10 self-end py-2.5 pr-5 pl-20 max-w-full bg-red-600 w-full max-md:pl-5">
        <span className="flex-auto text-4xl font-bold text-orange-50">
            VIEW ALL MENU
        </span>
    </button>
);

export default ViewAllMenuButton;
