/**
 * This code was generated by Builder.io.
 */
import React from "react";
interface MenuItemData {
    name: string;
    image: string;
    isHighlighted?: boolean;
}

const MenuItem: React.FC<MenuItemData> = ({ name, image, isHighlighted }) => {
    const baseClasses =
        "flex flex-col px-4 py-5 rounded-3xl h-[180px] w-[180px]";
    const highlightedClasses = isHighlighted
        ? "text-orange-50 bg-red-600"
        : "bg-orange-50";
    const textClasses = isHighlighted ? "" : "text-red-600";

    return (
        <div className={`${baseClasses} ${highlightedClasses}`}>
            <img
                src={image}
                alt={`${name} menu item`}
                className="object-contain self-center max-w-full aspect-[1.26] w-[108px] rounded-xl"
                loading="lazy"
            />
            <div className={`mt-7 text-center text-[15px] w-auto ${textClasses}`}>
                {name.includes(" ")
                    ? name.split(" ").map((word, index) => (
                          <React.Fragment key={index}>
                              {word}
                              {index !== name.split(" ").length - 1 && <br />}
                          </React.Fragment>
                      ))
                    : name}
            </div>
        </div>
    );
};

export default MenuItem;
