/**
 * This code was generated by Builder.io.
 */
import React from "react";
import MenuItem from "./MenuItem";
interface MenuItemData {
    name: string;
    image: string;
    isHighlighted?: boolean;
}

const menuItems: MenuItemData[] = [
    {
        name: "Burger",
        image: "https://cdn.builder.io/api/v1/image/assets/TEMP/94f2a72bb4d70b6659ac0dce0cd4f783ee21bcd8b6126a4fe5d5bdf8bbe79958?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109",
        isHighlighted: true,
    },
    {
        name: "Fried chicken",
        image: "https://cdn.builder.io/api/v1/image/assets/TEMP/4d61d331bc9883f20b266667c167d3b60018afd62352ecb3196ec4dcd15410fb?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109",
    },
    {
        name: "Doner with Grilled Chicken",
        image: "https://cdn.builder.io/api/v1/image/assets/TEMP/c194717f02f84dd635294e68be71ba40ac4443dcebfd82919e119a0d941ca345?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109",
    },
    {
        name: "Pizza",
        image: "https://cdn.builder.io/api/v1/image/assets/TEMP/ebf29bb7df0f7d0b008959875762603a189ce685c7f64a42ad0c88e2168a3042?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109",
    },
    {
        name: "Hot Dogs",
        image: "https://cdn.builder.io/api/v1/image/assets/TEMP/242509e61f95130fbaf7cc5229a4c3ad042d630088c650905766908d47a5d907?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109",
    },
    {
        name: "Chicken Skewers",
        image: "https://cdn.builder.io/api/v1/image/assets/TEMP/bddaa4c396d0eeb7d735e08b2a62f30dbecaaf2f5db4e0916cf32d88488c5e53?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109",
    },
    {
        name: "Greek Salad",
        image: "https://cdn.builder.io/api/v1/image/assets/TEMP/65983557c572d5b190ec07f300625adcdf324e60be687a533d87898521d31a2d?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109",
    },
    {
        name: "Dahi Puri",
        image: "https://cdn.builder.io/api/v1/image/assets/TEMP/2d29ab33c251cb4300032f2ac8541cf49a65fdac7247a1da7ca5456c10ed828f?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109",
    },
    {
        name: "Ice cream with Chocolate",
        image: "https://cdn.builder.io/api/v1/image/assets/TEMP/214ec1153fe3cc4ccda2cafa4ac1b9ca403bce7b1d7c71c49252d4868087bad7?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109",
    },
    {
        name: "Cocktail Glasses",
        image: "https://cdn.builder.io/api/v1/image/assets/TEMP/9a8d4745a7b57de2baa8fb0a8e62a61a320bf7b6e3a4e5703f524625a4b29016?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109",
    },
];

const SpecialsMenu: React.FC = () => {
    return (
        <div className="flex flex-col items-center justify-center w-full px-4 lg:px-[100px]">
            <h1 className="text-2xl md:text-3xl lg:text-4xl font-bold text-red-600 max-w-full text-center">
                SPECIALS MENU FOR ALL TIME
            </h1>
            <div className="flex flex-wrap gap-1 self-stretch lg:px-[100px] mt-8 text-lg md:text-xl lg:text-2xl text-red-600">
                {menuItems.map((item, index) => (
                    <MenuItem key={index} {...item} />
                ))}
            </div>
        </div>
    );
};

export default SpecialsMenu;
