/**
 * This code was generated by Builder.io.
 */
import React from "react";
import DeliveryInfo from "./DeliveryInfo";
import OrderButton from "./OrderButton";

interface DeliverySectionProps {
  title: string;
  subtitle: string;
  description: string;
  phoneNumber: string;
}

const DeliverySection: React.FC<DeliverySectionProps> = ({
  title,
  subtitle,
  description,
  phoneNumber,
}) => {
  return (
    <section className="flex gap-5 max-md:flex-col md:px-[100px]">
      <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
        <div className="flex flex-col w-full max-md:mt-10 max-md:max-w-full">
          <h2 className="self-center text-center text-xl font-bold text-red-600">
            Delivery
          </h2>
          <h1 className="mt-7 text-4xl font-bold text-red-600 max-md:mr-2.5 max-md:max-w-full">
            {title} <br />
            <span className="text-red-600">{subtitle}</span>
            <br />
          </h1>
          <p className="mt-9 text-lg text-slate-700 max-md:max-w-full">
            {description}
          </p>
          <div className="flex gap-10 mt-16 ml-8 max-w-full w-[421px] max-md:mt-10">
            <DeliveryInfo phoneNumber={phoneNumber} />
            <OrderButton />
          </div>
        </div>
      </div>
      <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/71f65d403357d306ae60de219b7ce1b795b8ca08951b644ca28fd0eead25f2c6?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109"
          alt="Delivery illustration"
          className="object-contain grow mt-12 w-full aspect-[1.43] max-md:mt-10 max-md:max-w-full"
        />
      </div>
    </section>
  );
};

export default DeliverySection;
