/**
 * This code was generated by Builder.io.
 */
import React from "react";

const OrderButton: React.FC = () => {
  return (
    <div className="flex flex-col flex-1 text-2xl text-orange-50 rounded-xl">
      <button className="px-5 py-3 bg-red-600 rounded-xl shadow-sm max-md:pl-5">
        Order Now
      </button>
    </div>
  );
};

export default OrderButton;
