/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { useSelector } from "react-redux";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";

interface CartSummaryProps {
    shipping: string;
}

const CartSummary: React.FC<CartSummaryProps> = ({ shipping }) => {
    const { id } = useSelector((state: any) => state.customerSlice);
    const { total } = useSelector((state: any) => state.cartSlice);
    const navigate = useNavigate();
    return (
        <section className="flex flex-col gap-2 px-20 pt-10 pb-11 mx-auto w-full text-red-600 bg-orange-50 max-md:px-5 max-md:mt-10 max-md:max-w-full">
            <h2 className="text-4xl font-bold">CART SUBTOTAL</h2>
            <div className="flex gap-10 justify-between mt-4">
                <span className="text-lg">Order Subtotal</span>
                <span className="text-lg">${total.toFixed(2)}</span>
            </div>
            <hr className="shrink-0 mt-3.5 max-w-full h-0.5 bg-red-600 border-2 border-red-600 border-solid w-full" />
            <div className="flex gap-5 justify-between mt-4 text-lg">
                <span>Shipping</span>
                <span>{shipping}</span>
            </div>

            <hr className="shrink-0 mt-3.5 max-w-full h-0.5 bg-red-600 border-2 border-red-600 border-solid w-full" />
            <div className="flex gap-5 justify-between mt-4 text-lg whitespace-nowrap">
                <span className="text-[40px] font-semibold">Total</span>
                <span>${total.toFixed(2)}</span>
            </div>
            <button
                onClick={() => {
                    if (!id) {
                        toast.info("Please login to continue");
                        return;
                    }
                    if (total === 0) {
                        toast.info("Please add items to your cart");
                        return;
                    }
                    navigate("/checkout");
                }}
                className="self-center px-10 py-5 mt-20 text-lg text-white bg-red-600 hover:bg-red-300 rounded-xl max-md:px-5 max-md:mt-10"
            >
                Proceed To Checkout
            </button>
        </section>
    );
};

export default CartSummary;
