/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SearchBar: React.FC = () => {
  return (
    <div className="flex gap-2.5 items-center self-stretch my-auto text-xl font-light text-green-800 whitespace-nowrap border-green-800 w-auto">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/63d5e6fd26d3de969af4d9bca9cad196d6aac11c0c0becbd41c6f2b76c4227a7?apiKey=e34b0bbc442149bfa463a424862e236a&"
        alt=""
        className="object-contain shrink-0 self-stretch my-auto aspect-square w-[30px]"
      />
      <div className="hidden md:block self-stretch my-auto ">Search</div>
    </div>
  );
};

export default SearchBar;
