/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FormSection from "./FormSection";
import FormInput from "./FormInput";
import { ICustomer } from "../../../types/ICustomer";

interface ProfileFormProps {
    customer: ICustomer;
}

const ProfileForm: React.FC<ProfileFormProps> = ({ customer }) => {
    return (
        <div className="flex flex-col sm:w-[60%] max-sm:w-full max-md:mt-10">
            <FormSection title="BASIC INFORMATION">
                <FormInput label="Full Name*" value={customer.fullName} />
                <FormInput label="Email Address" value={customer.email} />
                <FormInput label="Age*" value={String(customer.age) || "18"} />
                <FormInput label="Contact Number" value={customer.phone} />

                <FormInput label="Full Address" value="Dhaka, Bnagladesh" />
            </FormSection>
            <div className="bg-red-500 self-center px-8 py-4 mt-5 max-w-full text-2xl text-white rounded-xl w-auto max-md:px-5 max-md:mt-10">
                Save Setting
            </div>
        </div>
    );
};

export default ProfileForm;
