/**
 * This code was generated by Builder.io.
 */
import React from "react";
interface SidebarItemProps {
    setSidebar: (value: number) => void;
    id: number;
    label: string;
    isActive: boolean;
    link: string;
}

const SidebarItem: React.FC<SidebarItemProps> = ({setSidebar,id, label, isActive }) => {
    const baseClasses =
        "px-4 py-4 mt-4 text-2xl bg-orange-50 hover:bg-orange-200 border-t border-b border-solid border-y-red-600 text-slate-700 max-md:pr-5";
    const activeClasses =
        "border-red-600 border-solid border-l-[15px] border-l-red-600";
    return (
        <div
            onClick={() => setSidebar(id)}
            className={`${baseClasses} ${isActive ? activeClasses : ""}`}
        >
            {label}
        </div>
    );
};

export default SidebarItem;
