/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ItemDetail from "./Components/ItemDetail";
import FoodMenuSpecial from "./Components/FoodMenuSpecial/FoodMenuSpecial";
import FoodMenu from "./Components/FoodMenuNormal/FoodMenu";
import HeroSection from "../../components/top-title/HeroSection";

const items = {
    title: "Lorem Ipsum",
    detail: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiulgod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborumLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
    imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/443c9c548f4f60485edd7843abad7713979d075b25e755b5f71d41c1ba3594b3?placeholderIfAbsent=true&apiKey=e0522cabc",
};

const Detail: React.FC = () => {
    return (
        <main className="flex flex-col items-center">
            <HeroSection title={items.title} description=""/>
            <div className="w-screen h-auto flex flex-col justify-center items-center bg-main overflow-x-hidden gap-[50px] lg:px-0 px-[30px]">
                <ItemDetail detail={items.detail} imageSrc={items.imageSrc} />
                <span className="text-[30px] text-red-500">See more items</span>
                <FoodMenu />
                <FoodMenuSpecial />
            </div>
        </main>
    );
};

export default Detail;
