/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface InputFieldProps {
    label: string;
    type?: string;
    required?: boolean;
    value: string;
    onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
    onKeyPress?: (e: React.KeyboardEvent<HTMLInputElement>) => void;
}

const InputField: React.FC<InputFieldProps> = ({
    label,
    type = "text",
    required = false,
    value,
    onChange,
    onKeyPress
}) => {
    const id = label.toLowerCase().replace(/\s+/g, "-");

    return (
        <div className="mt-4">
            <label htmlFor={id} className="text-lg">
                {label} {required && "*"}
            </label>
            <input
                onKeyPress={onKeyPress}
                value={value}
                onChange={onChange}
                id={id}
                type={type}
                required={required}
                className="flex shrink-0 mt-2.5 max-w-full px-4 bg-white rounded-xl border-2 border-red-600 border-solid h-[50px] w-[300px]"
            />
        </div>
    );
};

export default InputField;
