/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import InputField from "./InputField";
import Button from "./Button";
import { apiLogin } from "../../../utils/auth/login.service";
import { useDispatch } from "react-redux";
import { useNavigate } from "react-router-dom";
import { login as reduxLogin } from "../../../redux/slice/user.slice";
import Loading from "./Loading";
import Swal from "sweetalert2";

interface LoginProps {
    // Add any props if needed
}

const Login: React.FC<LoginProps> = () => {
    const [isSending, setIsSending] = useState(false);
    const navigate = useNavigate();
    const dispatch = useDispatch();

    const [login, setLogin] = useState({
        email: "",
        password: "",
    });

    const handleLogin = async () => {
        setIsSending(true);
        const rs = await apiLogin(login);
        if (rs.status === 200) {
            dispatch(reduxLogin(rs.data));
            setIsSending(false);
            navigate("/");
        }else{
            Swal.fire({
                icon: "error",
                title: "Oops...",
                text: "Email or password is incorrect!",
            });
            setIsSending(false);
        }
    };

    return (
        <>
            {isSending && <Loading />}
            <section className="flex flex-col h-1/2 w-6/12 max-md:ml-0 max-md:w-full">
                <div className="flex flex-col items-start p-5 mx-auto w-full text-2xl text-red-600 bg-orange-50 max-md:mt-10 max-md:max-w-full">
                    <h2 className="text-4xl font-bold">Login</h2>
                    <div>
                        <InputField
                            value={login.email}
                            onChange={(e) =>
                                setLogin({ ...login, email: e.target.value })
                            }
                            label="Email address"
                            required
                        />
                        <InputField
                            onKeyPress={(e) => {
                                if (e.key === "Enter") {
                                    handleLogin();
                                }
                            }}
                            value={login.password}
                            onChange={(e) => {
                                setLogin({
                                    ...login,
                                    password: e.target.value,
                                });
                            }}
                            label="Password"
                            type="password"
                            required
                        />
                        <Button onClick={handleLogin}>Log in</Button>
                    </div>
                    <a href="#" className="mt-4 hover:text-red-200">
                        Forgot password?
                    </a>
                </div>
            </section>
        </>
    );
};

export default Login;
