/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { FoodItemProps } from "./types";

const FoodItem: React.FC<FoodItemProps> = ({
  title,
  description,
  price,
  imageSrc,
  imageAlt,
}) => {
  return (
    <article className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col w-full rounded-3xl max-md:mt-8 max-md:max-w-full">
        <div className="py-2.5 pr-2.5 pl-5 bg-orange-50 rounded-3xl shadow-sm max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            <div className="flex flex-col w-[73%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col items-start self-stretch my-auto text-xl font-bold text-slate-700 max-md:mt-9">
                <h2>{title}</h2>
                <p className="self-stretch mt-4 text-lg">{description}</p>
                <p className="mt-4">From ${price}</p>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-[27%] max-md:ml-0 max-md:w-full">
              <img
                loading="lazy"
                src={imageSrc}
                alt={imageAlt}
                className="object-contain shrink-0 max-w-full rounded-3xl aspect-square w-[150px] max-md:mt-5"
              />
            </div>
          </div>
        </div>
      </div>
    </article>
  );
};

export default FoodItem;
