/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Button from "./Button";

interface FeatureItemProps {
  title: string;
  description: string;
}

const FeatureItem: React.FC<FeatureItemProps> = ({ title, description }) => {
  return (
    <>
      <h3 className="mt-6 text-4xl font-bold text-red-600">{title}</h3>
      <p className="self-stretch mt-2.5 text-lg text-slate-700 max-md:max-w-full">
        {description}
      </p>
      <Button text="Read More" variant="secondary" />
    </>
  );
};

export default FeatureItem;
