/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ImageGrid: React.FC = () => {
  return (
    <div className="flex gap-5 max-md:flex-col">
      <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/5ffdee99fa563afb7acba24bbde98f1bc678eb610a4bd2f4adde299f0b97fa94?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109"
          alt="Restaurant interior"
          className="object-contain grow w-full aspect-[1.5] shadow-[0px_4px_4px_rgba(0,0,0,0.25)] max-md:mt-2.5"
        />
      </div>
      <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/5d3a6789a6ee08f49711fe22e0f7401d6686885a6f28f1e7d729f784fa241c07?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109"
          alt="Restaurant dish"
          className="object-contain grow w-full aspect-[1.5] shadow-[0px_4px_4px_rgba(0,0,0,0.25)] max-md:mt-2.5"
        />
      </div>
    </div>
  );
};

export default ImageGrid;
