/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SectionTitle from "./SectionTitle";
import ImageGrid from "./ImageGrid";

interface OurRestaurantProps {
  title: string;
  subtitle: string;
  description: string;
}

const OurRestaurant: React.FC<OurRestaurantProps> = ({
  title,
  subtitle,
  description,
}) => {
  return (
    <section className="flex gap-5 max-md:flex-col">
      <div className="flex flex-col w-[41%] max-md:ml-0 max-md:w-full">
        <div className="grow mt-20 max-md:mt-10 max-md:max-w-full">
          <ImageGrid />
        </div>
      </div>
      <div className="flex flex-col ml-5 w-[59%] max-md:ml-0 max-md:w-full">
        <div className="flex flex-col items-start font-bold text-slate-700 max-md:mt-10 max-md:max-w-full">
          <SectionTitle title={title} />
          <h2 className="mt-4 text-4xl">{subtitle}</h2>
          <p className="self-stretch mt-7 text-lg max-md:max-w-full">
            {description}
          </p>
        </div>
      </div>
    </section>
  );
};

export default OurRestaurant;
