/**
 * This code was generated by Builder.io.
 */
import React from "react";
import OurRestaurant from "./OurRestaurant";
import SuccessStory from "./SuccessStory";

const RestaurantPage: React.FC = () => {
  const ourRestaurantData = {
    title: "OUR RESTAURANT",
    subtitle: "For every special occasion there's heritaste",
    description:
      "Indignation and dislike men who are so beguiled demoralized by the charms of pleasure of the moment. Success Story.",
  };

  const successStoryData = {
    title: "Success Story",
    description:
      "Certain circumstances and owing to the claims of duty obligations of business it will frequently.",
    features: [
      {
        icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/2be4eefb8ac5e3874843dc469d5b0857a55d0c36d53a4cb04392df0c897070d0?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109",
        title: "Success Story",
        description:
          "Certain circumstances and owing to the claims of duty obligations of business it will frequently.",
      },
      {
        icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/9eca63c14c053ab211dacfff8f31f00259b26881f40735f3d9b05c9f2d9f28cf?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109",
        title: "Passionate Chefs",
        description:
          "Duty or the obligations of business it frequently occur pleasures have to be repudiated.",
      },
    ],
  };

  return (
    <main className="flex flex-col md:px-[100px] mt-[50px]">
      <OurRestaurant {...ourRestaurantData} />
      <SuccessStory {...successStoryData} />
    </main>
  );
};

export default RestaurantPage;
