/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SectionTitleProps {
  title: string;
}

const SectionTitle: React.FC<SectionTitleProps> = ({ title }) => {
  return <h3 className="text-xl text-red-600">{title}</h3>;
};

export default SectionTitle;
