/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FeatureItem from "./FeatureItem";

interface SuccessStoryProps {
    title: string;
    description: string;
    features: Array<{
        icon: string;
        title: string;
        description: string;
    }>;
}

const SuccessStory: React.FC<SuccessStoryProps> = ({
    features,
}) => {
    return (
        <section className="flex gap-5 max-md:flex-col">
            <div className="flex flex-col w-[41%] max-md:ml-0 max-md:w-full">
                <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/932ecb0b6d0de47ae2df2e045f6a1ae76705c511f32f8cc48579c190fcce2b05?placeholderIfAbsent=true&apiKey=e0522cabc7bc4885906fcb2658eca109"
                    alt="Success story illustration"
                    className="object-contain grow mt-2.5 w-full aspect-[1.47] shadow-[0px_4px_4px_rgba(0,0,0,0.25)] max-md:mt-10 max-md:max-w-full"
                />
            </div>
            <div className="flex flex-col ml-5 w-[59%] max-md:ml-0 max-md:w-full">
                <div className="max-md:mt-10 max-md:max-w-full">
                    <div className="flex gap-5 max-md:flex-col">
                        <div className="flex flex-col w-[15%] max-md:ml-0 max-md:w-full">
                            {features.map((feature, index) => (
                                <div
                                    key={index}
                                    className="flex flex-col justify-center px-5 py-6 mt-16 rounded-full border-red-600 border-solid border-[3px] stroke-[3px] stroke-red-600 max-md:mt-10"
                                >
                                    <img
                                        loading="lazy"
                                        src={feature.icon}
                                        alt=""
                                        className="object-contain aspect-square w-[50px]"
                                    />
                                </div>
                            ))}
                        </div>
                        <div className="flex flex-col ml-5 w-[85%] max-md:ml-0 max-md:w-full">
                            <div className="flex flex-col items-start w-full text-4xl font-bold text-red-600 max-md:mt-5 max-md:max-w-full">
                                {features.map((feature, index) => (
                                    <FeatureItem
                                        key={index}
                                        title={feature.title}
                                        description={feature.description}
                                    />
                                ))}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    );
};

export default SuccessStory;
