/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ServiceCard from "./ServiceCard";

interface SpecialServicesProps {
  services: Array<{
    title: string;
    description: string;
  }>;
}

const SpecialServices: React.FC<SpecialServicesProps> = ({ services }) => {
  return (
    <section className="mt-16 max-md:mt-10">
      <h2 className="text-4xl font-bold leading-10 text-slate-700 text-center">
        SPECIAL SERVICE
      </h2>
      <p className="mt-2 text-lg text-center text-red-600">
        What Special services we are offering now
      </p>
      <div className="mt-12 max-w-full w-[886px] mx-auto max-md:mt-10">
        <div className="flex gap-5 max-md:flex-col">
          {services.map((service, index) => (
            <ServiceCard
              key={index}
              title={service.title}
              description={service.description}
            />
          ))}
        </div>
      </div>
      <nav
        className="flex gap-2.5 mt-14 max-w-full w-[107px] mx-auto max-md:mt-10"
        aria-label="Service navigation"
      >
        {[...Array(4)].map((_, index) => (
          <button
            key={index}
            className={`flex shrink-0 w-5 h-5 rounded-full border-2 border-red-600 border-solid ${
              index === 1 ? "bg-red-600" : ""
            }`}
            aria-label={`Service ${index + 1}`}
          />
        ))}
      </nav>
    </section>
  );
};

export default SpecialServices;
