/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ShoppingCart from "./components/ShoppingCart/ShoppingCart";
import HeroSection from "../../components/top-title/HeroSection";

const AboutUs: React.FC = () => {
    return (
        <main className="flex flex-col items-center">
            <HeroSection title="My Cart" description="" />
            <ShoppingCart />
        </main>
    );
};

export default AboutUs;
