/**
 * This code was generated by Builder.io.
 */
import React from "react";

type ContactInfoProps = {
  icon: string;
  text: string;
  altText: string;

};

const ContactInfo: React.FC<ContactInfoProps> = ({ icon, text, altText }) => (
  <div className="flex gap-4 self-stretch text-center">
    <img
      loading="lazy"
      src={icon}
      alt={altText}
      className="object-contain shrink-0 my-auto w-[11px] aspect-[0.69] fill-red-600"
    />
    <div className="flex-auto w-[303px]">{text}</div>
  </div>
);

export default ContactInfo;
