/**
 * This code was generated by Builder.io.
 */
import React from "react";

type SocialIconProps = {
  src: string;
  alt: string;
};

const SocialIcon: React.FC<SocialIconProps> = ({ src, alt }) => (
  <img
    loading="lazy"
    src={src}
    alt={alt}
    className="object-contain shrink-0 aspect-square w-[25px]"
  />
);

export default SocialIcon;
